name    'sibds/codeception'
version '0.1.1'
source 'UNKNOWN'
author 'sibds'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
dependency 'tPl0ch/composer', '>= 1.3.0'
