<?php  //[STAMP] a815dbc5f3c78ef1bf88bcbe7c3397f3
namespace tests\codeception\frontend\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile



trait UnitTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
